### ISSUE TITLE
Posting the releases

### ISSUE THREAD

**Issue by retrography** [yujitach/MenuMeters#29] opened 2016-05-30 19:07 UTC
Would you mind posting the releases here (in the release section of your GitHub repo)? It will give your release more legitimacy if the binaries are served here rather than on your personal website. Your release is for now the de facto standard and the main release, so it merits a legit hosting, and inclusion in package managers such as homebrew cask.

**Comment by retrography** [comment] 2016-05-30 19:10
I just noticed CrystalIdea has released an official version finally.

**Comment by ranek** [comment] 2016-06-14 05:58
This appears to duplicate https://github.com/yujitach/MenuMeters/issues/11.

Homebrew Cask has included [`yujitach-menumeters`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/yujitach-menumeters.rb) since October 2015.

**Comment by yujitach** [comment] 2016-12-16 06:21
Duplicate of #11

**Closed by yujitach** 2016-12-16 06:21 UTC
Labels: duplicate
