### ISSUE TITLE
Files copy slows down when "Disc Activity Menu Meter" enabled

### ISSUE THREAD

**Issue by bobrosoft** [yujitach/MenuMeters#19] opened 2015-12-21 12:46 UTC
Hi there!

I definitely noticed files copy slowdown when "Display Disc Activity Menu Meter" is "on". Was under copy of 8GB file from my internal SSD to external USB Flash Drive. When I disabled "Disc Activity", copy speed returned back to normal (was near 100 times slower). When enabled -- slowed down again. My settings attached (update interval: 2 sec.). Maybe happens only with USB Flash Drives.

![2015-12-21 16 44 05](https://cloud.githubusercontent.com/assets/3481333/11930994/badb1fda-a7f9-11e5-90fd-2082c7ac1cac.png)

If you have time, you can check this.

**Comment by Nechoer** [comment] 2016-01-08 16:47
I confirm. I spent a week trying to figure why my time machine backup takes ages (on a gigabit ethernet connection did not manage to make a backup in 3 full days after 10.11.2 +XCode update which modified some 7Gbyte files)
Switched off disk access monitor and it flies! Is this related to the internal SSD disk? Interestingly network access does not seem to be influenced. I will test and report beck if it does.

**Comment by lipwak** [comment] 2016-01-12 23:10
Same as Nechoer here. In my case, it also caused Time Machine backups to fail repeatedly since installing it 2 days ago. After removing it from the preference panes backups worked. (Lost all my backups in the process of troubleshooting.) 

Throughput was very low/slow using it: single digit kb/s with occasional 3-4 mb/s even when connected to the Time Capsule by ethernet cable. Would LOVE to have this work so hope if can be fixed.

I was using the CPU, Disk and Network meters set to their default settings.

(MacBook Pro 15-inch Retina, Late 2013, SSD, 2.3 GHz Intel Core i7, OSX 10.11.2)

**Comment by mikegem** [comment] 2016-03-03 02:26
Same as Nechoer. Upgraded my MBPr from Yosemite to El Capitan, Time Machine stopped working. After several days of trying many things, I noticed MM network thruput on the laptop did not match MM network on a target Mini when copying files from laptop to Mini. Found Nechoer's comment here, removed MM from laptop. TM now working to backup laptop to Mini.

**Comment by lukehamburg** [comment] 2016-03-03 12:40
Does this bug only affect you if you enable network  monitoring in MenuMeters? I.e if all you have is a CPU meter displayed would it still occur?

**Comment by Nechoer** [comment] 2016-03-03 12:49
Well it appears me disabling network monitoring helps, but I removed completely MM ( although I loved this tool and thanks for porting it to 10.11!!!! I really appreciate people making things happen to others!!!) Right now I am running on very tight schadule, but if I can get a break I will retest.

**Comment by TomCooper3** [comment] 2016-03-28 16:05
I've been chasing an issue with backup over the network since upgrading to El Capitan.  Backup performance has been abysmal.  (Strangely when a disk is USB attached, local Time Machine backup is OK.)  I'm experimenting with removing MenuMeters to see if that was the issue.  

Support *did* have me try booting and backing up in safe mode - would that have disabled MenuMeters?

**Comment by mikegem** [comment] 2016-03-28 20:01
Booting in safe mode did not resolve the superslow Time Machine backup issue for me. Removing MenuMeters did. 
I would have thought safe boot would have disabled MM, but the TM issue continued even in safe boot until I removed MM.
Like you, I also found that TM backup to a local disk worked ok. It was only backup over my LAN that had problems. 

    On Monday, March 28, 2016 9:05 AM, TomCooper3 <notifications@github.com> wrote:
 

 I've been chasing an issue with backup over the network since upgrading to El Capitan. Backup performance has been abysmal. (Strangely when a disk is USB attached, local Time Machine backup is OK.) I'm experimenting with removing MenuMeters to see if that was the issue. Support did have me try booting and backing up in safe mode - would that have disabled MenuMeters?—

**Comment by TomCooper3** [comment] 2016-03-28 20:29
Thanks for the feedback!  
Removing menumeters DID significantly speed up backup over the network.

I still am having an issue where the backup size is FAR too large.   Backup is in progress but I believe that a single backup will be at least 2x the size of my disk.  Running the faster backup now, and will continue to troubleshoot with Apple Support.
 
Tom Cooper
tom.cooper3@gmail.com

**Comment by DavidFerrington** [comment] 2016-03-31 19:30
I've been having problems with Time Machine backups for 3 months. Some posted in the thread on Apple support about this and I turned of the Disk & Network meters and that's resolved it. Shame, but I didn't really use those meters much, so not too much of a problem.

**Comment by TomCooper3** [comment] 2016-03-31 19:47
Removal of menu meters solved my backup problems.  Annoying - today I
wanted to know why a VM was not responding, and without menu meters it's
almost impossible to quickly diagnose if it's network, disk or CPU
constrained.

**Comment by yujitach** [comment] 2016-04-01 08:49
I believe you can just turn off the disk meter to live without this bug. I'm also pretty sure about the place of the bug in the code now; the disk meter checks the empty space of the drive 10 times a second etc. so I need to do something with it.

**Comment by DavidFerrington** [comment] 2016-04-01 09:47
Ok, thank you for the confirmation. I believe you are correct. How about just ignoring a time capsule or the backup disk?
 -- David (from my iPhone)

**Comment by ajkavanagh** [comment] 2016-04-01 16:10
I can confirm the same bug (with Time Machine backups) and that just switching the disk monitoring off is sufficient to speed it up again.

**Comment by 2b-as** [comment] 2016-06-03 17:19
I can also confirm the bug with Time Machine, and that switching off Disk Activity Menu Meter returns the backup to normal speed.

**Comment by yujitach** [comment] 2016-12-17 07:35
Hi, the latest version, contributed by @jthlim ,  should solve this issue. Could you try the new version by compiling by yourself, or downloading it from http://member.ipmu.jp/yuji.tachikawa/MenuMetersElCapitan/zips/MenuMeters_1.9.3.zip , to see if it works?

**Comment by lipwak** [comment] 2016-12-18 20:35
1.9.2 seems to have fixed it for me. Haven't seen slow speeds, well, slower than usual, since about April, I think. 1.9.3 no different.

**Comment by fpavageau** [comment] 2016-12-19 07:54
👍 1.9.3 works for me as well, Time Machine is able to backup.

**Comment by yujitach** [comment] 2016-12-22 02:22
Thank you for checking it works. I close the issue.

**Closed** 2016-12-22 02:22 UTC
