### ISSUE TITLE
feature request: display physical cores

### ISSUE THREAD

**Issue by elaforge** [yujitach/MenuMeters#62] opened 2017-07-29 07:11 UTC
For CPU, when I uncheck "show average for multiple processors", I get 8 graphs, probably 4 cores * 2 virtual hyperthread ones.  This takes up too much space and crowds out other useful displays.  However, it's useful to have a separate graph for each physical cpu core so I can see if one is busy but others are not.  So it would be nice to have an option to combine graphs for each physical core, and get down to only 4 graphs.

Thanks!

**Comment by yujitach** [comment] 2017-12-27 02:11
Duplicate of #72. #72 is newer, but has a screenshot, so I decided to close this one instead.

**Comment by yujitach** [comment] 2019-11-01 13:42
#72 got contaminated by issues due to having multiple instances of MenuMeters running. So I close #72 instead and decided to reopen this one.

**Comment by yujitach** [comment] 2019-11-10 14:33
I found that https://github.com/open-mpi/hwloc allows me to see which logical cores belong to which physical core. So in principle this should allow me to combine hyperthreaded cores into physical cores...

**Comment by yujitach** [comment] 2019-12-01 05:49
My reading of https://github.com/open-mpi/hwloc/blob/master/hwloc/topology-darwin.c strongly suggests that the logical CPU _2n-1_ and _2n_ correspond to the physical core _n_ . I would simply show the odd-numbered logical CPU, then.

**Comment by yujitach** [comment] 2019-12-07 04:11
This option is provided in the new version 2.0.3, available via auto update

**Closed by yujitach** 2019-12-07 04:11 UTC
