### ISSUE TITLE
Server 5.0.4

### ISSUE THREAD

**Issue by cptcoolpro** [yujitach/MenuMeters#16] opened 2015-10-20 15:13 UTC
MenuMeters 1.9.1 seems to interfere with OS X Server 5 based Time Machine Service causing
- when run on server (OS X El Capitan 10.11.1 / Sever 5.0.4): making client time machine backups VERY slow.
- when run on clients (OS X El Capitan 10.11.1 & 10.11.1 beta (15b38b) ): same.
- when run on server and clients (OS X El Capitan / Server 5.0.4) : near to impossible to perform.

note: local time machine backups (e.g. on an external usb-HD) are not affected.

**Comment by gurple** [comment] 2015-11-12 09:02
I have noticed this interference as well.

**Comment by qrsouther** [comment] 2016-01-30 06:04
Also an ongoing issue here. Unfortunately, makes it very hard to justify keeping MenuMeters when Time Machine backups are now so unreliable.

**Comment by doxygen** [comment] 2016-02-18 19:38
I've filed a bug report on slow Time Machine perfomance at Apple, and after some troubleshooting they found MenuMeters was the culprit. Hoping this issue can one day be solved so I can use MenuMeters again.

**Comment by yujitach** [comment] 2016-02-19 12:49
@doxygen Did you get any more detailed comment from Apple, saying which API call of MenuMeters is the culprit?

**Comment by doxygen** [comment] 2016-02-19 20:36
No details yet. I've now explicitly asked for them. I'll forward any info I get.

**Comment by doxygen** [comment] 2016-02-28 14:20
This is the feedback I got. Not very concrete but I hope it is of some help:

> Engineering has determined that this is an issue for a third party to resolve.
> 
> MenuMeters is waking up every 280ms or so and doing something, and possibly triggering I/O on the AFP mount (there’s at least one sample showing this).
> It looks like it is probing periodicaly, so if that period is short enough and the length of time that it is in the probing state long enough, you will have very limited bandwidth through backupd.
> 
> Please inform the developers of MenuMeters to stop periodic probing.

**Comment by yujitach** [comment] 2016-02-29 01:36
Thanks, I'll have a look.

**Comment by rtboyce** [comment] 2016-06-04 22:21
Any progress on this, please?

**Comment by justinclift** [comment] 2016-09-03 21:28
Any idea if changing the polling period in the MenuMeter prefpane might help people having this issue?  eg change each of cpu/mem/disk/network to wait (say) 2 seconds between updates, instead of the subsecond defaults :smile:

**Comment by yujitach** [comment] 2016-12-17 07:35
Hi, the latest version, contributed by @jthlim ,  should solve this issue. Could you try the new version by compiling by yourself, or downloading it from http://member.ipmu.jp/yuji.tachikawa/MenuMetersElCapitan/zips/MenuMeters_1.9.3.zip , to see if it works?

**Comment by gurple** [comment] 2016-12-18 08:54
Nice! It seems to address the issue.

**Comment by justinclift** [comment] 2016-12-18 13:51
@yujitach Is that new 1.9.3 zip for Sierra only?

Asking because I tried it earlier today on my Sierra laptop where it's working fine.  On my main OSX desktop though, running El Capitan, it doesn't seem to work.  The PrefPane part loads when in System Preferences and allows things to the changed, it's just the "put things in the menu bar" isn't working at all.

Tried it both for all users (/Library/PreferencePanes), and just my own user (~/Library/PreferencePanes), but no difference.  It's also not a quarantine problem, as the com.apple.quarantine xattr isn't set on it.

**Comment by jthlim** [comment] 2016-12-18 15:43
It could well be my change on how images are displayed in the newer MenuMeters. I don't have an El Capitan system to test with. Are you able to build from source and test changes?

I'm wondering if this is the cause:

https://github.com/yujitach/MenuMeters/pull/39/commits/624605e178d4c29ab6057b7845f2b88984ba8760

**Comment by justinclift** [comment] 2016-12-18 16:26
Hmmm, looks like an Xcode project so I can probably try that out at some point if no-one else gets to it before me. :smile:

**Comment by justinclift** [comment] 2016-12-18 16:27
For the menu, I'm not yet sure.  I'll have to finish up what I'm doing first so I can reinstall the newer MenuMeters to try it out.  Likely later on today. :smile:

**Comment by yujitach** [comment] 2016-12-19 02:53
It might be that I mistakenly set the minimal OS requirement for the menu bar app to be 10.12. 
@justinclift , could you check if the app is at least running? Please open up the Activity Monitor and see if "MenuMetersApp" is running or not.

**Comment by yujitach** [comment] 2016-12-19 12:41
I noticed that I forgot to set the deployment target explicitly. Maybe by compiling on Sierra it only runs on Sierra. Now I set the deployment target to include El Capitan, recompiled and re-uploaded. @justinclift , could you re-download from http://member.ipmu.jp/yuji.tachikawa/MenuMetersElCapitan/zips/MenuMeters_1.9.3.zip and give it a try again?

**Comment by justinclift** [comment] 2016-12-19 17:44
Thanks guys, sorry for the delay.

@yujitach, yep that one's working in El Capitan on my desktop.  Yay! :smile:

**Comment by yujitach** [comment] 2016-12-20 00:31
Thanks for checking.

**Comment by justinclift** [comment] 2016-12-20 09:02
No worries at all.

Btw, the download link on your main web page is still pointing at the older release.  Not sure if that's supposed to be that way or not, though. :smile:

**Comment by yujitach** [comment] 2016-12-20 12:52
@justinclift I was going to update it after your confirmation, and I did that right now.

**Comment by justinclift** [comment] 2016-12-20 13:10
Awesome @yujitach.  Sorry for hassling. :wink:

**Comment by doxygen** [comment] 2016-12-20 21:21
Looks like it is working for me as well (on El capitan, with time machine running over the network). Great work. I'm happy to have menumeters back again!

**Comment by cptcoolpro** [comment] 2016-12-21 21:10
YEAH! it seems to work on sierra! thx alot!

**Comment by yujitach** [comment] 2016-12-22 02:22
Thank you for checking it works. I close the issue.

**Closed by yujitach** 2016-12-22 02:22 UTC

**Comment by aleksandrs-ledovskis** [comment] 2016-12-23 20:35
@yujitach 

Thanks for solving the OS X 10.11 issue, however I would suggest you to always bump version number when recompiling/reuploading different package. As seen above reference to homebrew-cask, not following this rule can create problem for package managers when checksum starts to deviate for any given version.

**Comment by yujitach** [comment] 2016-12-24 01:36
@aleksandrs-ledovskis Sorry about it, but my intension of uploading the preliminary 1.9.3 (which was later updated) and linking it not from my main webpage but from the issues page only was for people concerned of the particular issues to be able to test it, and I didn't expect that the preliminary 1.9.3 (which was later updated) to be registered to the homebrew-cask. Indeed, the original 1.9.3 didn't even run on El Capitan. I would suggest you to put the new version to the homebrew-cask only after it is linked from the main webpage. 

I know people ask me to put the "official" binary on the GitHub webpage rather than my personal webpage, using the release feature. Maybe I should do that, since it would correctly convey my intension which upload is to be "public" etc.  But I'm currently using an old script of mine that does the code-signing and the uploading to my personal webpage, and I don't have time to update that script ...

**Comment by justinclift** [comment] 2016-12-24 14:50
If it's a helpful thought, we faced the same problem a while ago about where to put new binaries that are just for testing, and not yet proper releases.

We made a "prerelease" directory on our download server, and put things in that for testing.  It seems to be a good approach, communicating the status of the binary well enough to stop confusion. :smile:
