### ISSUE TITLE
[Feature Request] Monitor Free Space instead of just Disk Activity

### ISSUE THREAD

**Issue by kokizzu** [yujitach/MenuMeters#255] opened 2021-10-14 03:12 UTC
Hi, it would be nicer if the disk monitor shows remaining disk space (eg. how many GB or % left on the partitions) instead of disk activity light.

**Comment by yujitach** [comment] 2021-11-17 02:51
This is the duplicate of https://github.com/yujitach/MenuMeters/issues/242 .

**Closed by yujitach** 2021-11-17 02:51 UTC
