### ISSUE TITLE
Networkmeter - switching connection does not work

### ISSUE THREAD

**Issue by AykutCevik** [yujitach/MenuMeters#24] opened 2016-02-16 12:04 UTC
I'm connected with my WiFi and the networkmeter works great!

But if I'm connected to a VPN, the VPN-connection is always 0 up/down, so I switch to the WiFi-connection and select "show this interface" via the menu - which is not working. VPN-connection is still selected and I can't change the interface for measuring.

Is there any solution?

Thank you very much for your fork btw!

**Comment by kingrhoton** [comment] 2016-04-02 08:50
Ditto!

**Comment by yujitach** [comment] 2016-12-16 06:22
Duplicate of #14

**Closed by yujitach** 2016-12-16 06:22 UTC
Labels: duplicate
